name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
        npm install
        node index.js fetch -u https://example.com -o ./output.txt 
        node index.js help 
        node index.js version       
        node index.js fetch -u https://example.com -r 20 -w 2000
        yarn add loh
        yarn global add loh
        npm i -g loh@latest
        loh fetch -u https://example.com -o ./output.txt
        loh help
        loh version
        loh fetch -u https://example.com -r 20 -w 2000
        npx loh
